name: c_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  equatable: ^2.0.5
  widget_with_codeview: ^3.1.0
  flutter_highlighter: ^0.1.1
  http: ^1.1.0
  archive: ^3.4.2
  path_provider: ^2.1.1
  settings_ui: ^2.0.2
  choice: ^2.0.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/
    - assets/


  fonts:
    - family: comic
      fonts:
        - asset: fonts/comic.ttf
